import { CreateWorkoutPlanSchema, type CreateWorkoutPlan } from '@/lib/shared/types';

export interface PlanFormValues {
  name: string;
  durationWeeks: number;
  sessionsPerWeek: number;
  description?: string;
}

const WORKOUT_DAYS: Array<'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday'> = [
  'monday',
  'tuesday',
  'wednesday',
  'thursday',
  'friday',
  'saturday',
  'sunday',
];

function pickWorkoutDays(count: number): typeof WORKOUT_DAYS[number][] {
  const clamped = Math.min(Math.max(count, 1), WORKOUT_DAYS.length);
  const selected: typeof WORKOUT_DAYS[number][] = [];

  for (let i = 0; i < clamped; i += 1) {
    selected.push(WORKOUT_DAYS[i]);
  }

  return selected;
}

export function buildPlanFromForm(form: PlanFormValues, userId: string): CreateWorkoutPlan {
  const templateId = crypto.randomUUID();
  const mainExerciseId = crypto.randomUUID();
  const exerciseId = crypto.randomUUID();
  const now = new Date().toISOString();

  const trimmedName = form.name.trim();
  const description = form.description?.trim();
  const durationWeeks = Math.max(4, Math.round(form.durationWeeks));
  const sessionsPerWeek = Math.max(1, Math.round(form.sessionsPerWeek));

  const workoutDays = pickWorkoutDays(sessionsPerWeek);
  const restDays = WORKOUT_DAYS.filter((day) => !workoutDays.includes(day));

  const weeklySchedule = workoutDays.reduce<Record<string, { workoutTemplateId: string; isRestDay: false; estimatedDuration: number }>>(
    (acc, day) => ({
      ...acc,
      [day]: {
        workoutTemplateId: templateId,
        isRestDay: false,
        estimatedDuration: 60,
      },
    }),
    {}
  );

  const plan: CreateWorkoutPlan = {
    userId,
    name: trimmedName,
    description: description || undefined,
    durationWeeks,
    sessionsPerWeek,
    primaryGoals: ['strength'],
    secondaryGoals: [],
    targetFitnessLevel: 'beginner',
    difficulty: 'beginner',
    estimatedSessionDuration: 60,
    macrocycle: {
      name: `${trimmedName} Macrocycle`,
      goal: 'build_strength',
      durationWeeks,
      phases: [
        {
          name: 'Foundation',
          weeks: durationWeeks,
          focus: 'base',
          description: 'Auto-generated phase for initial plan draft',
        },
      ],
    },
    mesocycles: [
      {
        name: 'Block 1',
        weekNumber: 1,
        focus: 'strength',
        volume: 'moderate',
        intensity: 'moderate',
        deloadWeek: false,
        keyMetrics: [],
      },
    ],
    microcycles: [
      {
        weekNumber: 1,
        workoutDays,
        restDays,
        pattern: 'accumulation',
      },
    ],
    workoutTemplates: [
      {
        id: templateId,
        createdAt: now,
        updatedAt: now,
        name: `${trimmedName} Template`,
        description: description || undefined,
        category: 'strength',
        difficulty: 'beginner',
        estimatedDuration: 60,
        targetMuscleGroups: ['full_body'],
        workoutType: 'strength',
        warmUpExercises: [],
        mainExercises: [
          {
            id: mainExerciseId,
            exerciseId,
            orderIndex: 0,
            phase: 'main',
            sets: [
              {
                setNumber: 1,
                setType: 'working',
                targetReps: 10,
                restPeriod: 90,
              },
            ],
            substitutions: [],
            modifications: [],
          },
        ],
        coolDownExercises: [],
        equipmentRequired: [],
        spaceRequired: 'moderate',
        tags: [],
        isActive: true,
        isPublic: false,
      },
    ],
    schedule: {
      startDate: now,
      timeZone: 'UTC',
      weeklySchedule,
      exceptions: [],
    },
    progressionRules: {
      progression: 'linear',
      autoGenerated: true,
    },
    aiMetadata: {
      source: 'manual_form_v2',
    },
    status: 'draft',
    locale: 'en',
    units: 'metric',
  };

  return CreateWorkoutPlanSchema.parse(plan);
}
