import React from 'react';
import Link from 'next/link';
import { WorkoutPlanList } from '@/components/workouts/plan-list';
import { NewPlanDialogTrigger } from '@/components/workouts/plan-new-dialog';

export default async function WorkoutPlansPage() {
  return (
    <section className="mx-auto flex w-full max-w-5xl flex-col gap-8 px-4 py-8 sm:px-6 sm:py-10 lg:px-0">
      <header className="flex flex-col gap-4 border-b border-slate-200 pb-6 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Planning</p>
          <h1 className="mt-2 text-3xl font-semibold text-slate-900">Workout Plans</h1>
          <p className="mt-2 text-sm text-slate-500">
            Manage the training programs generated by the AI or crafted manually.
          </p>
        </div>
        <div className="flex w-full flex-col gap-3 sm:w-auto sm:flex-row sm:items-center">
          <Link
            href="#"
            className="inline-flex w-full items-center justify-center rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700 transition hover:border-slate-300 hover:bg-slate-50 sm:w-auto"
          >
            Plan templates
          </Link>
          <NewPlanDialogTrigger />
        </div>
      </header>

      <div className="flex flex-col gap-4">
        <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
          <h2 className="text-lg font-semibold text-slate-900">Your plans</h2>
          <p className="text-sm text-slate-500">Auto-refreshes when you create a plan via the API.</p>
        </div>
        <WorkoutPlanList />
      </div>
    </section>
  );
}
